<?php
/**
 *
 * $Id: helper.php 1.0.0 2012-06-17 19:17:41 Christian Maioli Mackeprang $
 * @package	    Repartos 
 * @subpackage	Repartos - modulo
 * @version     1.0.0
 * @description 
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  Copyrighted Commercial Software
 * @author		  Christian Maioli Mackeprang
 * @author mail	mmchristian@gmail.com
 * @website		  -
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 * The module methods
 * -------------------------------
 * getItems()
 *
 */

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
 
/**
 * Example Module Helper
 *
 * @package		  Repartos
 * @subpackage	Repartos - modulo
 * @since 		  1.0.0
 * @class       ModRepartosHelper
 */ 

include_once( JPATH_ADMINISTRATOR.DS.'components'.DS.'com_repartos'.DS.'models'.DS."models.php" );

class ModRepartosHelper
{
	/**
	 * Do something getItems method
	 *
	 * @param 	
	 * @return
	 */
    public function getItems($cp)
    {
        $model = new RepartosModels();

        return $model->loadRecords('repartos', array('codigopostal' => $cp));
    } //end getItems
 
} // END ModRepartosHelper

?>