<?php
/**
 *
 * $Id: mod_repartos.php 1.0.0 2012-06-17 19:17:41 Christian Maioli Mackeprang $
 * @package	    Repartos 
 * @subpackage	Repartos - modulo
 * @version     1.0.0
 * @description 
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  Copyrighted Commercial Software
 * @author		  Christian Maioli Mackeprang
 * @author mail	mmchristian@gmail.com
 * @website		  -
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 */

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
 
// include the helper file
require_once(dirname(__FILE__).DS.'helper.php');
 
/**
 * Example to get a parameter from the module's configuration
 * $chanelCount = $params->get('chanelcount');
 */

$uri = & JFactory::getURI();
$doc = &JFactory::getDocument();
$doc->addScript( JURI::root(). 'modules/mod_repartos/scripts/default.js' );
$doc->addScriptDeclaration('var url = \'' . $uri->toString() . '\';');

$cp = JRequest::getVar('codigopostal', '');
$items = ModRepartosHelper::getItems($cp);

$tmpl = JRequest::getVar('repartoshidden','default');

$ajax = isset($_SERVER['HTTP_X_REQUESTED_WITH'])
    && (strcasecmp('XMLHttpRequest', $_SERVER['HTTP_X_REQUESTED_WITH']) === 0);

if($ajax) {
    ob_start();
    require(JModuleHelper::getLayoutPath('mod_repartos', $tmpl));
    $content = ob_get_clean();
    die($content);
} else {
    require(JModuleHelper::getLayoutPath('mod_repartos', $tmpl));
}
