<!--
/**
 * JS DOCUMENT
 *
 * $Id: default.js 1.0.0 2012-06-17 19:17:41 Christian Maioli Mackeprang $
 * @package	    Repartos 
 * @subpackage	Repartos - modulo
 * @version     1.0.0
 * @description 
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  Copyrighted Commercial Software
 * @author		  Christian Maioli Mackeprang
 * @author mail	mmchristian@gmail.com
 * @website		  -
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 */

/***     YOUR JAVSCRIPT CODE HERE     ***/

(function($) {
    $(document).ready(function() {
        $('#repartos_form').live('submit', function() {
            repartos.load($('#codigopostal').val(), 'itemlist');
            return false;
        });
        $('#repartos_reload').live('click', function() {
            repartos.load('');
            return false;
        });
    });
})(jQuery);

window.repartos = {
    'load': function(cp, hiddenval) {
        var hidden = hiddenval || 'default';
        jQuery('#repartos_module').load(url, {
            'codigopostal': cp,
            'repartoshidden': hidden
        });
    }
};
//-->