<?php
	/*
	** Generated by Joomla Admin Generator
	** Author: Christian Maioli Mackeprang
	** Email: mmchristian@gmail.com
	** 
	** Component:  com_repartos
	** File: install.com_repartos.php
	** Time: Mon, 18 Jun 2012 01:52:57
	*/

	// no direct access
	defined( '_JEXEC' ) or die( 'Restricted access' );

	/**
	 * Install
	 * @return unknown_type
	 */
	function com_install()
	{
		global $mainframe;
		$db =& JFactory::getDBO();
		$db_prefix = $mainframe->getCfg('dbprefix');
		$result = _runQueries($db);
		if(count($result)>=1)
		{
			foreach($result as $msg)
			{
				echo $msg."<br/>\n";
			}
		}else{
			echo "Install Component Success";
		}
	}
	
	/**
	 * Run SQL Query
	 * 
	 * @param object $db
	 * @return string
	 */
	function _runQueries($db)
	{
		
$installQueries[] = 'DROP TABLE IF EXISTS `#__repartos`';
$installQueries[] = 'CREATE TABLE `#__repartos` ( `id`  int(11) auto_increment, `fecha`  date, `codigopostal`  varchar(250),PRIMARY KEY  (`id`))ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8';
		$msg = array();
		if( count($installQueries) >=1 )
		{
			foreach ( $installQueries as $query ) {
				$db->setQuery( $query );
				$db->query();
				if ( $db->getErrorNum() ) {
					$msg[] = '<br/>' . $db->stderr();
				}
			}
		}
		return $msg;
	}

