<?php

	/*
	** Generated by Joomla Admin Generator
	** Author: Christian Maioli Mackeprang
	** Email: mmchristian@gmail.com
	** 
	** Component:  com_repartos
	** File: repartos.php
	** Time: Mon, 18 Jun 2012 01:52:57
	*/

	$c =& JRequest::getCmd('c','');
	$task =& JRequest::getCmd('task','show');
	$action =& JRequest::getCmd('action','');        

        if($c=='')
            $c = 'repartos';

	include_once( JPATH_COMPONENT_ADMINISTRATOR.DS.'controllers'.DS."$c.php" );
	include_once( JPATH_COMPONENT_ADMINISTRATOR.DS.'models'.DS."models.php" );
	include_once(JPATH_COMPONENT_ADMINISTRATOR.DS."models".DS."helper.php");
	include_once( JPATH_COMPONENT_ADMINISTRATOR.DS.'views'.DS."admin.$c.html.php" );

	$cotroller_name = ucfirst($c)."Controller";
	$controller = new $cotroller_name();

	switch(strtolower($task))
	{
		case 'add':
			$controller->editRecord(false); break;
		case 'edit':
			$controller->editRecord(true); break;
		case 'remove':
		case 'removeRecord':
			$controller->removeRecord(); break;
		case 'apply':
		case 'save':
		case 'save2new':
		case 'save2copy':
			$controller->saveRecord( $_POST, $action, strtolower($task) ); break;
		default:
			$controller->showRecord(); break;
	}

?>
