<?php
	/*
	** Generated by Joomla Admin Generator
	** Author: Christian Maioli Mackeprang
	** Email: mmchristian@gmail.com
	** 
	** Component:  com_repartos
	** File: uninstall.com_repartos.php
	** Time: Mon, 18 Jun 2012 01:52:57
	*/
// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

/**
 * Uninstall
 * @return unknown_type
 */
function com_uninstall()
{
	global $mainframe;
	$db =& JFactory::getDBO();
	$db_prefix = $mainframe->getCfg('dbprefix');
	$result = _runQueries($db);
	if(count($result)>=1)
	{
		foreach($result as $msg)
		{
			echo $msg."<br/>\n";
		}
	}else{
		echo "UnInstall Component Success";
	}
}

/**
 * Run sql queries
 * 
 * @param object $db
 * @return string msg
 */
function _runQueries($db)
{
	
$installQueries[] = 'DROP TABLE `#__repartos`';
	$msg = array();
	if( count($installQueries) >=1 )
	{
		foreach ( $installQueries as $query ) {
			$db->setQuery( $query );
			$db->query();
			if ( $db->getErrorNum() ) {
				$msg[] = '<br/>' . $db->stderr();
			}
		}
	}
	return $msg;
}

