<?php

	/*
	** Generated by Joomla Admin Generator
	** Author: Christian Maioli Mackeprang
	** Email: mmchristian@gmail.com
	** 
	** Component:  com_repartos
	** View: Render_HTML
	** File: admin.repartos.html.php
	** Time: Mon, 18 Jun 2012 01:52:57
	*/
	
	
	class Render_HTML
	{
		/**
		 * Show a form to add/edit a record
		 *
		 * @param boolean edit
		 * @param object row
		 * @param string image_path_form_select
		 */
		function editRecord($edit, $row, $image_path_from_select = '/images/')
		{
                    ?>
                    <form action="index.php" method="post" name="adminForm" enctype="multipart/form-data">
                        <div class="col width-60">
                            <fieldset class="adminform">
                                <legend><?php echo JText::_('Details'); ?></legend>
                                <table class="admintable">
                                    <tr>
                                        <td class="key">
                                            <label for="fecha">
                                                <?php echo JText::_("Fecha"); ?>:</label>
                                        </td>
                                        <td >
                                            <input class="inputbox" type="text" name="repartos[fecha]" id="fecha" size="60" maxlength="255" value="<?php echo (isset($row->fecha) ? $row->fecha : ""); ?>" /> <img class="calendar" src="templates/system/images/calendar.png" alt="calendar" onclick="return showCalendar('fecha', '%Y-%m-%d');" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="key">
                                            <label for="codigopostal">
                                                <?php echo JText::_("Codigopostal"); ?>:</label>
                                        </td>
                                        <td >
                                            <input class="inputbox" type="text" name="repartos[codigopostal]" id="codigopostal" size="60" maxlength="255" value="<?php if ($edit == true) echo $row->codigopostal; ?>" />
                                        </td>
                                    </tr>

                                </table>
                            </fieldset>
                        </div>

                        <div class="col width-40"></div>
                        <div class="clr"></div>
                        <input type="hidden" name="c" value="<?php echo JRequest::getVar('c') ?>" />
                        <input type="hidden" name="option" value="<?php echo JRequest::getVar('option') ?>" />
                        <input type="hidden" name="id" value="<?php echo is_object($row) ? $row->id : ''; ?>" />
                        <input type="hidden" name="task" value="<?php echo JRequest::getVar('task') ?>" />
                        <input type="hidden" name="action" value="<?php echo $edit == true ? 'edit' : 'add' ?>" />
                        <?php echo JHTML::_('form.token'); ?>
                        <?php JHTML::_('behavior.calendar'); ?>
                    </form>
                    <?php
		}

		/**
		 * A table show all records
		 *
		 * @param array rows
		 * @param int page
		 * @param array list
		 */
		function showRecord($rows, $page, $list = array())
		{
			?>
				<form action="index.php" method="post" name="adminForm">
					<table>
						<tr>
							<td align="left">Find <input type="text" name="keywords" /></td>
							<td align="right"></td>
						</tr>
					</table>
					<table class="adminlist">
					<thead>
						<tr>
							<th width="10">
								<?php echo JText::_( 'NUM' ); ?>
							</th>
							<th width="10">
								<input type="checkbox" name="toggle" value="" onclick="checkAll(<?php echo count( $rows );?>);" />
							</th>
							<th class="title">Fecha</th>
							<th class="title">Codigo Postal</th>
							<th class="title">Action</th>

						</tr>
					</thead>
					<tfoot>
						<tr>
							<td colspan="7">
								<?php echo $page->getListFooter(); ?>
							</td>
						</tr>
					</tfoot>
					<tbody>
						<?php
							$i=0; 
						if(count($rows)>=1){
							foreach($rows as $k=>$v){
								$checked 	= @JHTML::_('grid.checkedout',   $v, $i );
								?>
								<tr>
									<td><?php echo $page->getRowOffset( $i ); ?></td>
									<td><?php echo $checked?></td>
									<td><?php echo $v->fecha ?></td>
									<td><?php echo $v->codigopostal ?></td>
									<td width='10'><a href='index.php?option=com_repartos&c=repartos&task=edit&id=<?=$v->id?>'><img src='components/com_repartos/assets/images/edit.png'/></a></td>

								<?php 
								$i++;
							}
						}
						?>
					</tbody>
					</table>
				<input type="hidden" name="c" value="<?php echo JRequest::getVar('c')?>" />
				<input type="hidden" name="option" value="<?php echo JRequest::getVar('option')?>" />
				<input type="hidden" name="id" value="" />
				<input type="hidden" name="task" value="<?php echo JRequest::getVar('task')?>" />
				<input type="hidden" name="boxchecked" value="0" />
				<?php echo JHTML::_( 'form.token' ); ?>
				</form>
			<?php
		}

	}
?>
