<?php
/**
 *
 * $Id: default.php 1.0.0 2012-06-17 19:17:41 Christian Maioli Mackeprang $
 * @package	    Repartos 
 * @subpackage	Repartos - modulo
 * @version     1.0.0
 * @description 
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  Copyrighted Commercial Software
 * @author		  Christian Maioli Mackeprang
 * @author mail	mmchristian@gmail.com
 * @website		  -
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 */

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
?>
<!-- START Repartos - modulo MODULE -->

<div class="moduletable<?php echo $params->get('moduleclass_sfx'); ?>" id="repartos_module">
    <form action="<?php echo JRoute::_('index.php'); ?>" id="repartos_form">
        Código Postal: <input type="text" name="codigopostal" id="codigopostal" />
        <input type="submit" value="Buscar" />
        <input type="hidden" name="repartoshidden" value="repartoshidden" />
        <input type="hidden" name="option" value="<?php echo JRequest::getVar('option','com_virtuemart'); ?>" />
        <input type="hidden" name="view" value="<?php echo JRequest::getVar('view','index'); ?>" />
    </form> 
</div>

<!-- END Repartos - modulo MODULE -->