<?php
/**
 *
 * $Id: default.php 1.0.0 2012-06-17 19:17:41 Christian Maioli Mackeprang $
 * @package	    Repartos 
 * @subpackage	Repartos - modulo
 * @version     1.0.0
 * @description 
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  Copyrighted Commercial Software
 * @author		  Christian Maioli Mackeprang
 * @author mail	mmchristian@gmail.com
 * @website		  -
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 */

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' ); ?>
<!-- START Repartos - modulo MODULE -->

<?php if(empty($items)): ?>
    No se han encontrado coincidencias.
<?php else: ?>
    <table style="border-color: #8592B5; border-collapse: collapse" border="1" cellpadding="6">
        <tr>
            <th>Código Postal</th>
            <th>Fecha</th>
        </tr>
        <?php foreach($items as $item): ?>
        <tr>
            <td><?php echo $item->codigopostal; ?></td>
            <td><?php echo $item->fecha; ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<br /><br />
<a href="#" id="repartos_reload">Otra búsqueda</a>

<!-- END Repartos - modulo MODULE -->